# Generated by Django 2.2.4 on 2019-08-22 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizuser',
            name='overall_score',
            field=models.SmallIntegerField(default=0),
        ),
    ]
