# Generated by Django 2.2.4 on 2019-09-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='time',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
