# Generated by Django 2.2.4 on 2019-08-22 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quizuser_overall_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('answer_a', models.CharField(max_length=50)),
                ('answer_b', models.CharField(max_length=50)),
                ('answer_c', models.CharField(max_length=50)),
                ('answer_d', models.CharField(max_length=50)),
                ('correct', models.CharField(max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='quizuser',
            name='sana',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.ManyToManyField(to='quiz.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
