# Generated by Django 2.2.4 on 2019-10-15 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20191013_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='switch',
            field=models.BooleanField(default=False),
        ),
    ]
