# Generated by Django 2.2.4 on 2019-09-13 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_answer_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='train',
        ),
    ]
