# Generated by Django 2.2.4 on 2019-08-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20190822_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='train',
            field=models.BooleanField(default=True),
        ),
    ]
