# Generated by Django 2.2.4 on 2019-11-04 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_question_recommendation_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Asset'),
            preserve_default=False,
        ),
    ]
