# Generated by Django 2.2.4 on 2019-08-22 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import quiz.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_test_train'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct',
            field=quiz.models.IntegerRangeField(default=0),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='answers',
            field=models.ManyToManyField(to='quiz.Answer'),
        ),
    ]
