# Generated by Django 2.2.4 on 2019-08-25 22:08

from django.db import migrations
import os
import json


def add_questions(apps, schema_editor):
    if os.path.isfile('./questions.json'):
        questions_file = open('./questions.json', 'w')
        questions_json = questions_file.read()

        questions = json.loads(questions_json)

        Question = apps.get_model('quiz', 'Question')

        for question in questions:
            model = Question()
            model.text = question.text
            model.correct = question.correct

            model.answer_a = question.alternatives[0]
            model.answer_b = question.alternatives[1]
            model.answer_c = question.alternatives[2]
            model.answer_d = question.alternatives[3]
            model.answer_e = question.alternatives[4]

            model.save()

    else:
        print('questions.json was not found.')


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20190822_1934'),
    ]

    operations = [
        migrations.RunPython(add_questions)
    ]
