# Generated by Django 2.2.4 on 2019-08-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
