# Generated by Django 2.2.4 on 2019-08-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_test_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
