# Generated by Django 2.2.4 on 2019-08-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_test_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizuser',
            name='overall_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
